  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment

  Resources:
    CodeWithQuarkus:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: target/function.zip
        MemorySize: 256
        Timeout: 15
        Policies: AWSLambdaBasicExecutionRole
        AutoPublishAlias: live
        SnapStart:
          ApplyOn: PublishedVersions
